(function(g){var window=this;var Qva=function(a,b){a.sa("onAutonavCoundownStarted",b)},P4=function(a,b,c){var d=b.Ca();
g.J(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.uc(c?c:"mqdefault.jpg");var f=b instanceof g.ZA&&b.lengthSeconds?g.yM(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.kC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.ZA?b.za:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.il||g.xM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.ph(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+
c+")":""};b instanceof g.lC&&(d.playlist_length=b.getLength());a.update(d)},Q4=function(a,b){g.Q.call(this,{F:"div",
Z:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},S4=function(a){g.Q.call(this,{F:"div",
Z:["ytp-upnext","ytp-player-content"],P:{"aria-label":"{{aria_label}}"},L:[{F:"div",I:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{F:"span",I:"ytp-upnext-top",L:[{F:"span",I:"ytp-upnext-header",X:"Up Next"},{F:"span",I:"ytp-upnext-title",X:"{{title}}"},{F:"span",I:"ytp-upnext-author",X:"{{author}}"}]},{F:"a",I:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Play next video"},L:[{F:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},L:[{F:"circle",
I:"ytp-svg-autoplay-circle",P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",I:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",I:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",I:"ytp-upnext-bottom",L:[{F:"span",I:"ytp-upnext-cancel"},{F:"span",I:"ytp-upnext-paused",X:"Autoplay is paused"}]}]});
this.api=a;this.cancelButton=null;this.D=this.o["ytp-svg-autoplay-ring"];this.A=this.notification=this.u=this.suggestion=null;this.B=new g.H(this.Kn,5E3,this);this.C=0;var b=this.o["ytp-upnext-cancel"];this.cancelButton=new g.Q({F:"button",Z:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancel autoplay"},X:"Cancel"});g.A(this,this.cancelButton);this.cancelButton.na("click",this.pI,this);this.cancelButton.da(b);g.A(this,this.B);g.CL(this.api,this.element,this,18788);this.M(this.o["ytp-upnext-autoplay-icon"],
"click",this.hM);this.sA();this.M(a,"autonavvisibility",this.sA);this.M(a,"mdxnowautoplaying",this.AL);this.M(a,"mdxautoplaycanceled",this.BL);this.M(a,"mdxautoplayupnext",this.QC);R4(this)&&(a=(a=g.iL(g.bL(this.api)))?a.lF():null)&&this.QC(a);g.J(this.element,"ytp-upnext-mobile",this.api.O().o)},U4=function(a,b){a.u||(g.Vo("a11y-announce","Up Next "+a.suggestion.title),a.C=(0,g.M)(),a.u=new g.H(function(){T4(a,b)},25),T4(a,b),Qva(a.api,b||g.P(a.api.O().experiments,"autoplay_time")||1E4));
g.In(a.element,"ytp-upnext-autoplay-paused")},R4=function(a){return 3===a.api.getPresentingPlayerType()},T4=function(a,b){var c=b||g.P(a.api.O().experiments,"autoplay_time")||1E4,d=Math.min(Rva(a),c);
c=Math.min(d/c,1);a.D.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&!R4(a)?a.select(!0):a.u&&a.u.start()},Rva=function(a){return(0,g.M)()-a.C},W4=function(a){V4(a);
a.C=(0,g.M)();T4(a);g.I(a.element,"ytp-upnext-autoplay-paused")},V4=function(a){a.u&&(a.u.dispose(),a.u=null)},Sva=function(a){Q4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.Q({F:"div",I:"ytp-subscribe-card",L:[{F:"img",I:"ytp-author-image",P:{src:b.Td}},{F:"div",I:"ytp-subscribe-card-right",L:[{F:"div",I:"ytp-author-name",X:b.author},{F:"div",I:"html5-subscribe-button-container"}]}]});g.A(this,this.u);this.u.da(this.element);this.subscribeButton=new g.gR("Subscribe",null,"Unsubscribe",null,!0,!1,b.Pg,b.subscribed,"trailer-endscreen",null,null,a);g.A(this,this.subscribeButton);this.subscribeButton.da(this.u.o["html5-subscribe-button-container"]);
this.hide()},X4=function(a){var b=a.O(),c=g.wt||g.Ah?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.Q.call(this,{F:"a",Z:e,P:{href:"{{url}}",target:d?b.D:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{F:"div",I:"ytp-videowall-still-image",P:{style:"{{background}}"}},{F:"span",I:"ytp-videowall-still-info",L:[{F:"span",I:"ytp-videowall-still-info-bg",L:[{F:"span",I:"ytp-videowall-still-info-content",P:c,L:[{F:"span",I:"ytp-videowall-still-info-title",X:"{{title}}"},{F:"span",I:"ytp-videowall-still-info-author",
X:"{{author_and_views}}"},{F:"span",I:"ytp-videowall-still-info-live",X:"Live"},{F:"span",I:"ytp-videowall-still-info-duration",X:"{{duration}}"}]}]}]},{F:"span",Z:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",I:"ytp-videowall-still-listlabel-length",L:[" (",{F:"span",X:"{{playlist_length}}"},")"]}]},{F:"span",Z:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{F:"span",I:"ytp-videowall-still-listlabel-length",X:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.A=new g.zr(this);g.A(this,this.A);this.na("click",this.onClick);this.na("keypress",this.C);this.A.M(a,"videodatachange",this.B);g.DL(a,this.element,this);this.B()},Y4=function(a){Q4.call(this,a,"videowall-endscreen");
var b=this;this.K=a;this.B=0;this.stills=[];this.C=this.videoData=this.suggestions=null;this.D=this.J=!1;this.H=null;this.A=new g.PQ(this);g.A(this,this.A);this.G=new g.H(function(){g.I(b.element,"ytp-show-tiles")},0);
g.A(this,this.G);var c=new g.Q({F:"button",Z:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Previous"},L:[g.SM()]});g.A(this,c);c.da(this.element);c.na("click",this.wH,this);this.table=new g.Gu({F:"div",I:"ytp-endscreen-content"});g.A(this,this.table);this.table.da(this.element);c=new g.Q({F:"button",Z:["ytp-button","ytp-endscreen-next"],P:{"aria-label":"Next"},L:[g.TM()]});g.A(this,c);c.da(this.element);c.na("click",this.vH,this);this.u=new S4(a);g.A(this,this.u);g.AL(this.player,this.u.element,
4);this.hide()},Z4=function(a){return g.BL(a.player)&&a.qw()&&!a.C},Tva=function(a,b){return(0,g.Hc)(b.suggestions,function(c){c=g.AM(a.K.O(),c);
g.A(a,c);return c})},$4=function(a){var b=a.ot();
b!==a.J&&(a.J=b,a.player.T("autonavvisibility"))},a5=function(a){g.ML.call(this,a);
this.endScreen=null;this.listeners=new g.zr(this);g.A(this,this.listeners);this.o=a.O();Uva(a)?this.endScreen=new Y4(this.player):this.o.Ya?this.endScreen=new Sva(this.player):this.endScreen=new Q4(this.player);g.A(this,this.endScreen);g.AL(this.player,this.endScreen.element,4);this.ZB();this.listeners.M(a,"videodatachange",this.ZB,this);this.listeners.M(a,g.jC("endscreen"),this.sH,this);this.listeners.M(a,"crx_endscreen",this.tH,this)},Uva=function(a){a=a.O();
return a.ya&&!a.Ya};
g.r(Q4,g.Q);g.h=Q4.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.qw=function(){return!1};
g.h.ot=function(){return!1};
g.h.yy=function(){return!1};g.r(S4,g.Q);g.h=S4.prototype;g.h.Kn=function(){this.notification&&(this.B.stop(),this.fb(this.A),this.A=null,this.notification.close(),this.notification=null)};
g.h.sA=function(){g.Ku(this,g.cL(this.api));g.GL(this.api,this.element,g.cL(this.api))};
g.h.YL=function(){window.focus();this.Kn()};
g.h.hide=function(){g.Q.prototype.hide.call(this)};
g.h.select=function(a){a=void 0===a?!1:a;if(g.O(this.api.O().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ca(),this.Kn(),this.notification=new Notification("Up Next",{body:b.title,icon:b.uc()}),this.A=this.M(this.notification,"click",this.YL),this.B.start())}V4(this);this.api.nextVideo(!1,a)};
g.h.hM=function(a){!g.Be(this.cancelButton.element,g.kp(a))&&g.RN(a,this.api)&&this.select()};
g.h.pI=function(){g.eL(this.api,!0)};
g.h.AL=function(a){R4(this);this.show();U4(this,a)};
g.h.QC=function(a){R4(this);this.suggestion&&this.suggestion.Ca().videoId===a.Ca().videoId||(this.suggestion=a,P4(this,a,"hqdefault.jpg"))};
g.h.BL=function(){R4(this);V4(this);this.hide()};
g.h.Y=function(){V4(this);this.Kn();g.Q.prototype.Y.call(this)};g.r(Sva,Q4);g.r(X4,g.Q);X4.prototype.select=function(){var a=this.suggestion.Ca().videoId,b=this.suggestion.getPlaylistId();(g.BT(this.api.app,a,this.suggestion.Rb,b,void 0,void 0)||this.api.ia("web_player_endscreen_double_log_fix_killswitch"))&&g.FL(this.api,this.element)};
X4.prototype.onClick=function(a){g.RN(a,this.api,this.u,this.suggestion.Rb||void 0)&&this.select()};
X4.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.pp(a)||(this.select(),g.op(a))}};
X4.prototype.B=function(){var a=this.api.getVideoData(),b=this.api.O();this.u=a.pc?!1:b.u};g.r(Y4,Q4);g.h=Y4.prototype;g.h.create=function(){Q4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=Tva(this,a),this.videoData=a);this.Jg();this.A.M(this.player,"appresize",this.Jg);this.A.M(this.player,"onVideoAreaChange",this.Jg);this.A.M(this.player,"videodatachange",this.xH);this.A.M(this.player,"autonavchange",this.qt);this.A.M(this.player,"autonavcancel",this.uH);a=this.videoData.autonavState;a!==this.H&&this.qt(a);this.A.M(this.element,"transitionend",this.qN)};
g.h.destroy=function(){g.Br(this.A);g.Me(this.stills);this.stills=[];this.suggestions=null;Q4.prototype.destroy.call(this);g.In(this.element,"ytp-show-tiles");this.G.stop();this.H=this.videoData.autonavState};
g.h.qw=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){Q4.prototype.show.call(this);g.In(this.element,"ytp-show-tiles");this.player.O().o?g.zn(this.G):this.G.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.eL(this.player,!1);Z4(this)?($4(this),2===this.videoData.autonavState?this.player.O().ia("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):U4(this.u):3===this.videoData.autonavState&&W4(this.u)):(g.eL(this.player,!0),$4(this))};
g.h.hide=function(){Q4.prototype.hide.call(this);W4(this.u);$4(this)};
g.h.qN=function(a){g.kp(a)===this.element&&this.Jg()};
g.h.Jg=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=g.rL(this.K,!0,this.K.isFullscreen()),b=g.cC(this.K);b&&(b=b.oc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,y=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&y)n-=q*m,e+=2;else if(u)n-=
t*m,b+=2;else if(y)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;c=this.player.O().ia("web_player_no_endscreen_crop")?1:1.21;m*=g.Rd(a.width/m||1,1,c);n*=g.Rd(a.height/n||1,1,c);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Ph(a,m,n);g.xh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.suggestion=f;P4(c,f,"hqdefault.jpg");g.J(this.element,
"ytp-endscreen-takeover",Z4(this));$4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),q=g.Sd(q+this.B,l),0!==t){u=this.stills[c];u||(u=new X4(this.player),this.stills[c]=u,a.appendChild(u.element));y=Math.floor(n*k/e);var B=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-y-4,E=Math.floor(m*(f+t)/b)-B-4;g.Fh(u.element,B,y);g.Ph(u.element,E,D);g.xh(u.element,"transitionDelay",(k+f)/20+"s");g.J(u.element,"ytp-videowall-still-mini",
1===t);g.J(u.element,"ytp-videowall-still-large",2<t);t=u;q=this.suggestions[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.O(),y=g.Gn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",P4(t,q,y),g.Iy(u)&&(u=q.ph(),u=g.Cd(u,g.lI({},"emb_rel_end")),t.oa("url",u)),(q=(q=q.Rb)&&q.itct)&&g.EL(t.api,t.element,q));c++}g.J(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ye(e.element),g.Le(e);this.stills.length=c}};
g.h.xH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.suggestions=Tva(this,a),this.videoData=a,this.Jg())};
g.h.vH=function(){this.B+=this.stills.length;this.Jg()};
g.h.wH=function(){this.B-=this.stills.length;this.Jg()};
g.h.yy=function(){return!!this.u.u};
g.h.qt=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,V4(this.u),this.Ka()&&this.Jg()):(this.D=!0,this.Ka()&&Z4(this)&&(2===a?U4(this.u):3===a&&W4(this.u)))};
g.h.uH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.GL(this.K,this.stills[a].element,!0);this.qt(1)}else this.C=null,this.D=!1;this.Jg()};
g.h.ot=function(){return this.Ka()&&Z4(this)};g.r(a5,g.ML);g.h=a5.prototype;g.h.Zy=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Uva(this.player)||b;var c=a.uj||g.Ry(a.Ta),d=g.VS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Yy=function(){return this.endScreen.ot()};
g.h.fG=function(){return this.Yy()?this.endScreen.yy():!1};
g.h.Y=function(){g.GR(this.player.app,"endscreen",void 0);g.ML.prototype.Y.call(this)};
g.h.load=function(){g.ML.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.ML.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.sH=function(a){this.Zy()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.tH=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.ZB=function(){g.GR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.gC(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.gC(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.wL(this.player,[a,b])};g.aM.endscreen=a5;})(_yt_player);
